### ISSUE TITLE
Seba, te puedo hacer una consulta?

### ISSUE THREAD

**Issue by Jotax10** [argorar/Volafile-Preview#1]
Estuve probando el volafile preview, hace unos meses lo tenia instalado y funcionaba joya, ahora no te cargas las imágenes, todas salen con el error (el STOP), tendrás idea que puede estar fallando en el código? porque no puedo encontrar el error. 

Saludos!

**Comment by argorar** [comment]
Te comparto la fuente original que está actualizada, [aquí](https://github.com/RealDolos/volascripts/blob/master/volanail.user.js) (Para instalar dar click en el botón Raw)
